### ISSUE TITLE
Custom theme support

### ISSUE THREAD

**Issue by rwhogg** [PerBothner/DomTerm#17]
It would be nice to be able to load CSS from an arbitrary file. For Terminator, I usually use a black background with green text, so it would be nice to be able to customize this without directly modifying DomTerm's CSS files.

I am working on this, but it's gone nowhere as of yet and I only have so much time, so if you're able to do this yourself, feel free.

**Comment by PerBothner** [comment]
At the prototyping level, you can just tweak style/domterm-default.css to your preferences.

I would like to have a UI to enable and disable different stylesheets: A popup with a file-selector to add an/or replace active stylesheets, and a way to remember user preferences. That is part of us the UI "chrome", so not something I have focused on, because it depends on which front-end(s) we up with - though we might be able to do it with just JavaScript in DomTerm core.

However, it occurs to me now that it would be useful to implement escape sequences to load new stylesheets, as well as enable/disable them. Then we could write a little shell script that emits these scap sequences. For example:
dtstyle --add stylesheet-name filename
dtstyle --enable stylesheet-name
dtstyle --disable stylesheet-name

**Comment by PerBothner** [comment]
I'm continuing to think of this, and design it in my head.  If nothing else, it will be a nice "bling" feature. Basically, there are two sub-tasks: (1) An escape sequence protocol for displaying and managing stylesheets, along with changes to terminal.js to implement it. (2) A user application to send and reads these escape sequences.  The latter I will probably write in Java.

**Comment by kbrock** [comment]
I like the preferences for the mac terminal. you give it the rgb for each of the colors and the display uses the rgb for display.  seems similar to your `css` suggestion.

**Comment by PerBothner** [comment]
I guess I should finish this.  The dtstyle utility and related support is most of the way there
(It is certainly possible to just call dtstyle --add-rule many times), but it would be good to have a simple way to load an entire css file.

**Comment by PerBothner** [comment]
You can now load CSS from an arbitrary file:

    $ dtstyle --load-stylesheet "sname" "fname"

Read a stylesheet from fname (or standard input if "fname" is "-"), and uploading.
The "sname" is used to identity the new stylesheet, including replcing previously uploaded ones.

See the documentation.

**Comment by rwhogg** [comment]
Cool! Really excited to hear about this, sorry I never had the time to test it out.

On April 12, 2016 3:40:27 PM PDT, Per Bothner <notifications@github.com> wrote:
>Closed #17.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PerBothner/DomTerm/issues/17#event-624921876

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
