### ISSUE TITLE
Unable to build DomTerm

### ISSUE THREAD

**Issue by turbopape** [PerBothner/DomTerm#21]
Hi, thank you for this promising piece of work (I'm playing around with kawa too these days, so really thank you!).

I nevertheless have issues building DomTerm On Linux ubuntu 15.10:

I configured with websockets 

./configure --with-java_websocket=/home/rafik/work/installs/TooTallNate-Java-WebSocket-58d1778/dist/java_websocket.jar

Then make gives me an error:
org/domterm/websocket/DomServer.java:198: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: org/domterm/ClassBackend.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Anything wrong with my procedure?

Keep on with the great work,

Rafik

**Comment by PerBothner** [comment]
First, the documentation is a bit unclear (I updated it just now): You don't actually need to specify the path to java_websocket.jar (or the --with-java_websocket option at all) since the default is to use the copy checked into github.

That said, I'm puzzled you would get the error, since Java-WebSocket code doesn't appear to have changed in a while.

Note there is a WebSocketServer.java in the DomTerm sources, but that is no longer used - it is from when DomTerm used a different WebSockets server.  I should probably remove it.

**Comment by turbopape** [comment]
Hi,

Thank you for your reponse, I removed the path to java_websocket and now it
works all right.


By the way, I also posted a question in kawa's mailing list to ask what
developement environment is the most used for kawa.

I tried Slime/Swank but it seems a little broken at times.

Thank you very much,

Cheers !

2016-02-18 17:20 GMT+00:00 Per Bothner <notifications@github.com>:
